// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NotificationHub is an autogenerated mock type for the NotificationHub type
type NotificationHub struct {
	mock.Mock
}

// NotifyUser provides a mock function with given fields: userID, message
func (_m *NotificationHub) NotifyUser(userID int64, message interface{}) {
	_m.Called(userID, message)
}

// NewNotificationHub creates a new instance of NotificationHub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationHub {
	mock := &NotificationHub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
