// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase

import mock "github.com/stretchr/testify/mock"

// MockNotificationHub is an autogenerated mock type for the NotificationHub type
type MockNotificationHub struct {
	mock.Mock
}

// NotifyUser provides a mock function with given fields: userID, message
func (_m *MockNotificationHub) NotifyUser(userID int64, message interface{}) {
	_m.Called(userID, message)
}

// NewMockNotificationHub creates a new instance of MockNotificationHub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationHub {
	mock := &MockNotificationHub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
