definitions:
  github_com_ssklv_mixfood-order-service_internal_domain.CreateOrderInput:
    properties:
      address_id:
        type: integer
      delivery_time:
        type: string
      items:
        items:
          $ref: '#/definitions/github_com_ssklv_mixfood-order-service_internal_domain.OrderItem'
        type: array
    type: object
  github_com_ssklv_mixfood-order-service_internal_domain.Order:
    properties:
      address_id:
        type: integer
      created_at:
        type: string
      delivery_time:
        type: string
      id:
        type: integer
      items:
        items:
          $ref: '#/definitions/github_com_ssklv_mixfood-order-service_internal_domain.OrderItem'
        type: array
      status:
        type: string
      total_price:
        type: number
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  github_com_ssklv_mixfood-order-service_internal_domain.OrderItem:
    properties:
      id:
        type: integer
      order_id:
        type: integer
      price:
        type: number
      product_id:
        type: integer
      quantity:
        type: integer
    type: object
  github_com_ssklv_mixfood-order-service_internal_domain.UpdateStatusInput:
    properties:
      status:
        type: string
    type: object
  internal_handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  internal_handlers.MessageResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/admin/orders:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_ssklv_mixfood-order-service_internal_domain.Order'
            type: array
      security:
      - BearerAuth: []
      summary: Получить все заказы (Только админ)
  /api/admin/orders/{id}/status:
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID заказа
        in: path
        name: id
        required: true
        type: integer
      - description: Статус
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_ssklv_mixfood-order-service_internal_domain.UpdateStatusInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handlers.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_handlers.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/internal_handlers.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Обновить статус заказа (Только админ)
  /api/orders:
    get:
      parameters:
      - description: Лимит записей
        in: query
        name: limit
        type: integer
      - description: Смещение
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_ssklv_mixfood-order-service_internal_domain.Order'
            type: array
      security:
      - BearerAuth: []
      summary: Получить список заказов пользователя
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные заказа
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_ssklv_mixfood-order-service_internal_domain.CreateOrderInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_ssklv_mixfood-order-service_internal_domain.Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_handlers.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Создать новый заказ
swagger: "2.0"
